-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 21:56:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Types` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `TypeId` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `StartDate` DATE NULL,
  `FinishDate` DATE NULL,
  `Deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `UserId_idx` (`UserID` ASC),
  INDEX `TypeId_idx` (`TypeId` ASC),
  CONSTRAINT `UserId`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TypeId`
    FOREIGN KEY (`TypeId`)
    REFERENCES `mydb`.`Types` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
